import React, {useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import * as I from 'lucide-react';
import './styles.css';

const routes={home:'Página Principal - Clínica de Psicología',booking:'Agenda en Línea',dashboard:'Panel de Pacientes',payments:'Pagos Pendientes',reminder:'Recordatorio de Pago'};
const routeFromHash=()=>Object.keys(routes).includes(location.hash.slice(1))?location.hash.slice(1):'home';

function App(){
 const [page,setPage]=useState(routeFromHash());
 const [transition,setTransition]=useState('');
 const go=(next,kind='push')=>{setTransition(kind); setTimeout(()=>{location.hash=next;setPage(next);scrollTo(0,0);setTransition('');},160)};
 useEffect(()=>{const h=()=>setPage(routeFromHash());addEventListener('hashchange',h);return()=>removeEventListener('hashchange',h)},[]);
 useEffect(()=>{window.handleAction=(message)=>{if(message==='Reminder sent to Sofia Castro')go('reminder','slide-up')};const b=document.querySelector('[data-reminder]');if(b)b.setAttribute('onclick',"handleAction('Reminder sent to Sofia Castro')")});
 return <div className={`app ${transition}`}><Header page={page} go={go}/><main>{page==='home'?<Home go={go}/>:page==='booking'?<Booking/>:page==='dashboard'?<Dashboard/>:page==='payments'?<Payments go={go}/>:<Reminder go={go}/>}</main><Footer page={page}/></div>
}
function Header({page,go}){return <header><button className="brand" onClick={()=>go('home','push-back')}><span className="brandmark">✦</span>Psyche<span>Care</span></button><nav><a className={page==='home'?'active':''} onClick={()=>go('home','push-back')}>Home</a><a className={page==='dashboard'?'active':''} onClick={()=>go('dashboard',page==='home'?'push':'push-back')}>Dashboard</a><a className={page==='payments'?'active':''} onClick={()=>go('payments',page==='reminder'?'push-back':'push')}>Payments</a></nav><div className="head-actions"><I.Bell size={20}/><span className="avatar">AV</span><button className="primary small" onClick={()=>go('booking')}>Book Now</button></div></header>}
const Button=({children,onClick,secondary=false})=><button className={secondary?'secondary':'primary'} onClick={onClick}>{children}</button>;
function Home({go}){return <><section className="hero"><div className="hero-copy"><span className="eyebrow"><I.ShieldCheck/> Atención psicológica profesional</span><h1>Tu bienestar emocional empieza <em>hoy.</em></h1><p>Un espacio seguro, cercano y confidencial para comprenderte, sanar y construir la vida que deseas.</p><div className="buttons"><Button onClick={()=>go('booking')}>Reservar cita <I.ArrowUpRight/></Button><Button secondary>Conoce al equipo</Button></div><div className="trust"><b>4.9</b><span>★★★★★<small>Más de 500 pacientes acompañados</small></span></div></div><div className="hero-visual"><div className="portrait"><div className="person">👩🏻‍⚕️</div><span className="bubble b1">Tu espacio seguro</span><span className="bubble b2">✓ Profesionales certificados</span></div></div></section><section className="section"><div className="section-head"><span className="kicker">NUESTROS SERVICIOS</span><h2>Apoyo pensado para ti</h2><p>Cada proceso es único. Encuentra la modalidad que mejor acompaña tu momento.</p></div><div className="cards">{[[I.UserRound,'Terapia individual','Un espacio personal para trabajar ansiedad, autoestima y bienestar emocional.'],[I.HeartHandshake,'Terapia de pareja','Reconstruyan la comunicación y fortalezcan sus vínculos en un entorno imparcial.'],[I.Users,'Talleres grupales','Comparte experiencias y herramientas en una comunidad cálida y respetuosa.']].map(([Icon,t,d])=><article className="service" key={t}><span className="icon"><Icon/></span><h3>{t}</h3><p>{d}</p><a>Saber más <I.ArrowRight/></a></article>)}</div></section><section className="cta"><span>EMPIEZA TU PROCESO</span><h2>Dar el primer paso puede cambiarlo todo.</h2><p>Estamos aquí para acompañarte, a tu ritmo y sin juicios.</p><Button onClick={()=>go('booking')}>Reservar cita</Button></section></>}
function Booking(){const [service,setService]=useState(0),[time,setTime]=useState('11:30 AM'),[confirmed,setConfirmed]=useState(false);let services=[['Terapia individual','50 minutos · $75'],['Terapia de pareja','60 minutos · $95'],['Evaluación inicial','Primera consulta · $50']];return <section className="page narrow"><span className="kicker">AGENDA EN LÍNEA</span><h1>Agenda tu próxima sesión</h1><p className="lead">Elige el tipo de apoyo y el horario que mejor se adapte a ti.</p><div className="booking-card"><div className="steps"><b>1 <span>Servicio</span></b><b>2 <span>Horario</span></b><b>3 <span>Confirmación</span></b></div><h2>¿Cómo podemos acompañarte?</h2><div className="service-options">{services.map((s,i)=><button className={service===i?'selected':''} onClick={()=>setService(i)} key={s[0]}><I.HeartPulse/><b>{s[0]}</b><small>{s[1]}</small></button>)}</div><div className="schedule"><div><h3>Noviembre 2026</h3><div className="calendar"><b>L</b><b>M</b><b>X</b><b>J</b><b>V</b><b>S</b><b>D</b>{[2,3,4,5,6,7,8,9,10,11,12,13,14,15].map(n=><span className={n===5?'day':''}>{n}</span>)}</div></div><div><h3>Horarios disponibles</h3><div className="times">{['09:00 AM','10:00 AM','11:30 AM','02:00 PM'].map(t=><button className={time===t?'selected':''} onClick={()=>setTime(t)}>{t}</button>)}</div></div></div><div className="booking-summary"><span><I.CalendarCheck/><small>Tu selección</small><b>{services[service][0]} · 5 Nov, {time}</b></span><Button onClick={()=>setConfirmed(true)}>{confirmed?'¡Cita confirmada!':'Confirmar cita'}</Button></div></div></section>}
const patients=[['Elena Aranda','Hoy, 10:00 AM','Confirmado'],['Ricardo Mendoza','Hoy, 11:30 AM','Pendiente'],['Lucía Castro','Ayer, 4:00 PM','Completado'],['Javier Vargas','Mañana, 9:00 AM','Confirmado']];
function Dashboard(){return <section className="page"><span className="kicker">PANEL DE PACIENTES</span><h1>Buenos días, Dr. Valencia</h1><p className="lead">Aquí tienes el resumen de tu actividad para hoy.</p><div className="stats">{[[I.CalendarDays,'Citas de la semana','24'],[I.WalletCards,'Pagos pendientes','12'],[I.MessageSquare,'Mensajes nuevos','08']].map(([Icon,l,v])=><article><Icon/><span><small>{l}</small><b>{v}</b></span></article>)}</div><div className="dashboard-grid"><div className="panel"><div className="panel-title"><h2>Próximos pacientes</h2><a>Ver calendario</a></div><div className="patient-table">{patients.map((p,i)=><div><span className="avatar">{p[0].split(' ').map(x=>x[0]).join('')}</span><b>{p[0]}</b><span>{p[1]}</span><em className={p[2].toLowerCase()}>{p[2]}</em><I.FileText/></div>)}</div></div><div><div className="wellbeing"><span className="kicker">BIENESTAR</span><h2>Promedio de bienestar</h2><b>7.8</b><div className="bars">{[40,62,55,80,68,48,35].map(h=><i style={{height:h}}/>)}</div><p>La tendencia de mejora se mantiene constante.</p></div><div className="quick"><h3>Acciones rápidas</h3><button>Nueva nota clínica →</button><button>Exportar facturas ↓</button><button>Configurar horario ⚙</button></div></div></div></section>}
const payments=[['Elena Martínez','24 Oct, 2026','$120.00','Vencido'],['Julián Rivera','26 Oct, 2026','$85.00','Pendiente'],['Sofia Castro','27 Oct, 2026','$150.00','Procesando'],['Alejandro Ortiz','28 Oct, 2026','$95.00','Vencido']];
function Payments({go}){return <section className="page"><div className="title-row"><div><span className="kicker">FINANZAS</span><h1>Pagos pendientes</h1><p className="lead">Gestiona facturas pendientes y mantén tus ingresos al día.</p></div><div className="total"><I.Wallet/><span><small>TOTAL PENDIENTE</small><b>$12,450.00</b></span></div></div><div className="filters"><label><I.Search/><input placeholder="Buscar paciente..."/></label><button><I.Calendar/> Últimos 30 días</button><button><I.Filter/> Todos los estados</button><button className="export"><I.Download/> Exportar</button></div><div className="payments-table"><div className="table-head"><span>Paciente</span><span>Fecha de sesión</span><span>Importe</span><span>Estado</span><span>Acciones</span></div>{payments.map((p,i)=><div className="payment-row"><span><i className="avatar">{p[0].split(' ').map(x=>x[0]).join('')}</i><b>{p[0]}</b></span><span>{p[1]}</span><b>{p[2]}</b><em className={p[3].toLowerCase()}>{p[3]}</em><span><button aria-label={`Enviar recordatorio a ${p[0]}`} data-reminder={i===2?'true':undefined} onClick={i===2?()=>go('reminder','slide-up'):undefined}><I.Mail/></button><button>Cobrar</button></span></div>)}</div><div className="insights"><article><h3>Salud de pagos</h3><div className="bars">{[55,35,48,28,70].map(h=><i style={{height:h}}/>)}</div><p>La recaudación subió un 12% este mes.</p></article><article><I.Sparkles/><div><h3>Automatiza tus recordatorios</h3><p>Reduce los pagos atrasados con avisos inteligentes y empáticos.</p><Button>Configurar automatización</Button></div></article></div></section>}
function Reminder({go}){return <section className="page narrow reminder"><div className="reminder-hero"><span><I.BellRing/></span><h1>Recordatorio de pago</h1><p>PsycheCare · Departamento de facturación</p></div><div className="letter"><h2>Hola <b>Sofia Castro,</b></h2><p>Esperamos que te encuentres bien. Te escribimos para recordarte que tienes un <strong>pago pendiente</strong> correspondiente a tu sesión de terapia de pareja.</p><div className="invoice"><span><I.Calendar/><small>FECHA DE SESIÓN</small><b>27 de octubre, 2026</b></span><span><I.Wallet/><small>MONTO PENDIENTE</small><b>$150.00 USD</b></span><span><small>ESTADO DE CUENTA</small><em>Pendiente</em><p>Vencimiento: 30 oct, 2026</p></span></div><div className="letter-actions"><Button>Pagar ahora</Button><Button secondary>Ver detalles</Button></div><hr/><i>“Tu bienestar mental es nuestra prioridad. Si tienes alguna duda, estamos para ayudarte.”</i><div><a>Contactar soporte</a> · <a onClick={()=>go('booking')}>Agendar Cita</a></div></div></section>}
function Footer(){return <footer><div><button className="brand">Psyche<span>Care</span></button><p>Acompañándote hacia el bienestar mental con profesionales verificados.</p></div><div><b>Servicios</b><a>Terapia individual</a><a>Terapia de pareja</a><a>Evaluaciones</a></div><div><b>Ayuda</b><a>Centro de ayuda</a><a>Preguntas frecuentes</a><a>Privacidad</a></div><div><b>Contacto</b><a>soporte@psychecare.com</a><small>© 2026 PsycheCare Clinic.</small></div></footer>}
createRoot(document.getElementById('root')).render(<App/>);
